version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  build-win:
    description: Build application with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Build w/ Release configuration"
          command: dotnet.exe build --configuration Release
      - run:
          name: "Compress build result"
          command: tar cf .\bin\Release\Release.tar .\bin\Release\net5.0
      - store_artifacts:
          path: .\bin\Release\Release.tar
workflows:
  build-windows:
    jobs:
      - build-win
      
